const userTypes = {
	SET_CURRENT_USER: "SET_CURRENT_USER",
	SIGN_IN_SUCESS: "SIGN_IN_SUCESS",
	SIGN_UP_SUCESS: "SIGN_UP_SUCESS",
	SIGN_UP_ERROR: "SIGN_UP_ERROR",
	RESET_PASSWORD_SUCESS: "RESET_PASSWORD_SUCESS",
	RESET_PASSWORD_ERROR: "RESET_PASSWORD_ERROR",
	RESET_AUTH_FORMS: "RESET_AUTH_FORMS"
};

export default userTypes;
