const productsTypes = {
	ADD_NEW_PRODUCT_START: "ADD_NEW_PRODUCT_START",
	FETCH_PRODUCTS_START: "FETCH_PRODUCTS_START",
	SET_PRODUCTS: "SET_PRODUCTS",
	DELETE_PRODUCT_START: "DELETE_PRODUCT_START",
	FETCH_PRODUCT_START: "FETCH_PRODUCT_START",
	SET_PRODUCT: "SET_PRODUCT",
	UPDATE_PRODUCT_VOTE_START: "UPDATE_PRODUCT_VOTE_START",
	FETCH_LATEST_PRODUCTS_START: "FETCH_LATEST_PRODUCTS_START",
	SET_LATEST_PRODUCTS: "SET_LATEST_PRODUCTS",
	FETCH_VALIDATION_PRODUCTS_START: "FETCH_VALIDATION_PRODUCTS_START",
	SET_VALIDATION_PRODUCTS: "SET_VALIDATION_PRODUCTS",
	UPDATE_PRODUCT_DETAILS_START: "UPDATE_PRODUCT_DETAILS_START"
};

export default productsTypes;
