/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({
	caseColor,
	glassColor,
	movementColor,
	crownColor,
	braceletColor
}) {
	const group = useRef();
	const { nodes } = useGLTF("/watch.glb");

	return (
		<group ref={group} dispose={null}>
			<mesh geometry={nodes["website_-_Bezel"].geometry}>
				<meshPhysicalMaterial
					//map={colorMap}
					color={caseColor ? "lightGrey" : "black"}
					clearcoat="1.0"
					metalness="0.9"
					clearcoatRoughness="0.1"
					roughness="0.5"
					envMaps="reflection"
				/>{" "}
			</mesh>
			<mesh geometry={nodes["website_-_Case"].geometry}>
				<meshPhysicalMaterial
					//map={colorMap}
					color={caseColor ? "lightGrey" : "black"}
					clearcoat="1.0"
					metalness="0.9"
					clearcoatRoughness="0.1"
					roughness="0.5"
				/>{" "}
			</mesh>
			<mesh geometry={nodes["website_-_CaseBack"].geometry}>
				<meshPhysicalMaterial
					//map={colorMap}
					color={caseColor ? "lightGrey" : "black"}
					clearcoat="1.0"
					metalness={caseColor ? "0.9" : "0"}
					clearcoatRoughness="0.1"
					roughness="0.5"
				/>{" "}
			</mesh>
			<mesh geometry={nodes["website_-_Crown"].geometry}>
				<meshPhysicalMaterial
					//map={colorMap}
					color={crownColor ? "grey" : "black"}
					clearcoat="1.0"
					metalness={crownColor ? "0.9" : "0"}
					clearcoatRoughness="0.1"
					roughness="0.5"
					envMaps="reflection"
				/>{" "}
			</mesh>
			<mesh geometry={nodes["website_-_Dial"].geometry}>
				<meshPhysicalMaterial
					//map={colorMap}
					color={braceletColor ? "grey" : "black"}
					clearcoat="1.0"
					metalness={braceletColor ? "0.9" : "0"}
					clearcoatRoughness="0.1"
					roughness="0.5"
					envMaps="reflection"
				/>{" "}
			</mesh>
			<mesh geometry={nodes["website_-_Glass"].geometry}>
				<meshPhysicalMaterial
					//map={colorMap}
					color={glassColor ? "lightBlue" : "black"}
					clearcoat="1.0"
					opacity={glassColor ? "0.6" : "1"}
					metalness="0"
					transmission={glassColor ? "1.0" : "0"}
					clearcoatRoughness="0.1"
					roughness="0.2"
					ior="1"
					reflectivity="0.5"
					envMaps="reflection"
				/>{" "}
			</mesh>
			<mesh
				geometry={nodes["website_-_Hours"].geometry}
				material={nodes["website_-_Hours"].material}
			>
				<meshPhysicalMaterial
					//map={colorMap}
					color={braceletColor ? "grey" : "black"}
					clearcoat="1.0"
					metalness={braceletColor ? "0.9" : "0"}
					clearcoatRoughness="0.1"
					roughness="0.5"
					envMaps="reflection"
				/>{" "}
			</mesh>
			<mesh geometry={nodes["website_-_Minutes"].geometry}>
				<meshPhysicalMaterial
					//map={colorMap}
					color={braceletColor ? "grey" : "black"}
					clearcoat="1.0"
					metalness={braceletColor ? "0.9" : "0"}
					clearcoatRoughness="0.1"
					roughness="0.5"
					envMaps="reflection"
				/>{" "}
			</mesh>
			<mesh geometry={nodes["website_-_Part_9"].geometry}>
				<meshPhysicalMaterial
					//map={colorMap}
					color={movementColor ? "grey" : "black"}
					clearcoat="1.0"
					metalness={movementColor ? "0.9" : "0"}
					clearcoatRoughness="0.1"
					roughness="0.5"
					envMaps="reflection"
				/>{" "}
			</mesh>
		</group>
	);
}

useGLTF.preload("/watch.glb");
